
echo -e "Default \e[30mBlack 1"
echo -e "Default \e[31mRed 2"
echo -e "Default \e[32mGreen 3"
echo -e "Default \e[33mYellow 4"
echo -e "Default \e[34mBlue 5"
echo -e "Default \e[35mMagenta 6"
echo -e "Default \e[36mCyan 7"
echo -e "Default \e[37mLight gray 8"
echo -e "Default \e[90mDark gray 9"
echo -e "Default \e[91mLight red 10"
echo -e "Default \e[92mLight green 11"
echo -e "Default \e[93mLight yellow 12"
echo -e "Default \e[94mLight blue 13"
echo -e "Default \e[95mLight magenta 14"
echo -e "Default \e[96mLight cyan 15"
echo -e "Default \e[97mWhite 16"
echo -e "Default \e[39mDefault"
